import esbuild from "esbuild";
import builtinModules from "builtin-modules";
import { execFileSync } from "child_process";
import { readFileSync } from "fs";
import process from "process";

const prod = process.argv[2] === "production";
const manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
let commit = "unknown";

try {
  commit = execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
} catch {
  // A source archive or other non-Git build environment has no commit hash.
}

const buildOptions = {
  banner: {
    js: "/*THIS IS A GENERATED/BUNDLED FILE BY ESBUILD*/",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  define: {
    __VG_VERSION__: JSON.stringify(String(manifest.version)),
    __VG_COMMIT__: JSON.stringify(commit),
    __VG_BUILT_AT__: JSON.stringify(new Date().toISOString()),
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "ES2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
};

if (prod) {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  esbuild
    .context(buildOptions)
    .then((ctx) => ctx.watch())
    .catch(() => process.exit(1));
}
